export const CREATE_EVENT_SUCCESS = "CREATE_EVENT_SUCCESS";
export const OPEN_CREATE_EVENT_FORM = "OPEN_CREATE_EVENT_FORM";
export const CLOSE_CREATE_EVENT = "CLOSE_CREATE_EVENT";
export const SELECT_FILTER = "SELECT_FILTER";
export const SAVE_EVENTLIST_LOCAL_STORAGE = "SAVE_EVENTLIST_LOCAL_STORAGE";